version: "3.3"

networks:
   paperplane:
      driver: bridge

services:
   paperplane:
      build: .
      links:
         - mongoserver
      networks:
         - paperplane
      restart: always
   mongoserver:
      image: bitnami/mongodb
      networks:
         - paperplane
      restart: always
      environment:
         - MONGODB_USERNAME=paperplane
         - MONGODB_PASSWORD=paperplane
         - MONGODB_DATABASE=userbot
