version: "3.7"

networks:
   paperplane:
      driver: bridge

services:
   paperplane:
      build: .
      environment: 
         PATH: '/app/bin:$PATH'
      working_dir: /app
      volumes: 
         - "./userbot.session:/app/userbot.session"
         - "./config.env:/app/config.env"
      links:
         - mongoserver
      networks:
         - paperplane
      depends_on: 
         - mongoserver
      restart: unless-stopped
   mongoserver:
      image: bitnami/mongodb
      networks:
         - paperplane
      restart: unless-stopped
      environment:
         - MONGODB_USERNAME=paperplane
         - MONGODB_PASSWORD=paperplane
         - MONGODB_DATABASE=userbot
